### ISSUE TITLE
example.py calculates 219 while the right answer should be 131

### ISSUE THREAD

**Issue by liangbingzhao** [Araachie/frechet_video_distance-pytorch-#1]
Hi, thx for your implementation. But I find that running example.py, the fvd calculated by your implementation is 219, but Google said that should be 131, can you help fix this?

**Comment by liangbingzhao** [comment]
another question: whether the video length should be 15? I tried 8 and 5, all failed

**Comment by JunyaoHu** [comment]
> Hi, thx for your implementation. But I find that running example.py, the fvd calculated by your implementation is 219, but Google said that should be 131, can you help fix this?

您好，请问您是在哪里看到计算结果应为131的，我使用我代码的计算结果是134，虽然不一致，但是比较相似。

Hello, may I ask where did you see that the calculation result should be 131? I used my code to calculate the result is 134, although not consistent, but similar.

code: [link](https://github.com/JunyaoHu/frechet_video_distance_calculation)

**Comment by liangbingzhao** [comment]
@JunyaoHu  sorry, I forget where I saw that.
